spring:
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    freemarker:
        cache: false
    jackson:
        serialization:
            fail-on-empty-beans: false