spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: 123
    h2:
        console:
        enabled: true
        path: /h2-console
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
        ddl-auto: update
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    freemarker:
        cache: false
    jackson:
        serialization:
            fail-on-empty-beans: false
#     jwt:
#         access-secret: ChatProjectSpringBootAccessSecret
#         access-header: Authorization_Access
#         access-prefix: Access
#         access-token-validity-in-seconds: 3600
#         refresh-secret: ChatProjectSpringBootRefreshSecret
#         refresh-header: Authorization_Refresh
#         refresh-prefix: Refresh
#         refresh-token-validity-in-seconds: 15 * 24 * 3600
jwt:
    access-secret: ChatProjectSpringBootAccessSecret
    access-header: Authorization_Access
    access-prefix: Access
    access-token-validity-in-seconds: 3600
    refresh-secret: ChatProjectSpringBootRefreshSecret
    refresh-header: Authorization_Refresh
    refresh-prefix: Refresh
    refresh-token-validity-in-seconds: 1296000 # 15 * 24 * 3600


